Moving into main issues: 2, 5, 6, 9
coronado-fi/coronado-jvm pull request #13
Opened 2022-08-22 00:29 UTC by jnmtwelve

I wanted to pull in just the maven setup related issues to the main branch. The goal is to align main with prototype minus dokka and kotlin.

2022-08-22 00:55 UTC, pr3d4t0r requested changes

2022-08-22 00:55 UTC, pr3d4t0r commented on pom.xml
> +            <email>coronado.project@numo.com</email>
FYI - this email doesn't exist yet, so we may need to modify it "soon" -- let me figure this one out.  We have coronado.fi and all I need to do is configure the actual domain, domain name resolution, and SMTP for it to .forward to whoever.  You may leave it as-is, or change it to something like info.jvm@coronado.fi or whatever you think it's appropriate.

2022-08-22 00:55 UTC, pr3d4t0r commented on pom.xml
> +</project>
This is often considered a no-no; in my code I always leave a \n at the end as suggested here (old habits from assembly development and some weird C compilers still want that).  Your call.

2022-08-22 00:55 UTC, pr3d4t0r commented on pom.xml
> +    <version>0.0.1-SNAPSHOT</version>
Please change this to 1.0.0, no SNAPSHOT.  I'm aware that POM likes it like this, let's roll with the actual version number.  We won't publish this to Maven Central or other indices for a while anyway.

2022-08-22 00:55 UTC, pr3d4t0r commented on pom.xml
> +        The full API documentation is available from https://api.partners.dev.tripleupdev.com/docs.
Please expand this comment to add that it's based on the Coronado wrapper reference implementation at https://github.com/coronado-fi/coronado - the triple full documentation is becoming redundant and even noxious because it has a lot of inconsistencies and issues that Coronado PY and JVM will hide.  That's one of the main business goals of Coronado.

2022-08-23 01:32 UTC, jnmtwelve commented on pom.xml
> +            <email>coronado.project@numo.com</email>
I'll change it to info.jvm@coronado.fi

2022-08-25 20:05 UTC, kinabalunumo approved these changes
LGTM

2022-08-25 20:45 UTC, pr3d4t0r approved these changes

2022-08-25 20:46 UTC, merged